language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install: "pip install python-scipy python-numpy csc-pysparse networkx divisi2"
# command to run tests
script: nosetests
